### ISSUE TITLE
configparser.NoSectionError: No section: 'tox'

### ISSUE THREAD

**Issue by jayvdb** [tox-dev/tox-pip-extensions#29]
If tox.ini exists and does not have a `[tox]` section, tox-pip-extensions causes an error.

```py
/usr/lib/python3.8/site-packages/tox_pip_extensions.py:51: in tox_configure
    for k, v in cfg.items('tox'):
```

This prevents building test cases like those in the main tox repo which dont include a `[tox]` section.

**Comment by asottile** [comment]
yeah this was written long before tox files could be valid without a `[tox]` section -- are you interested in sending a patch to make that optional?
