### ISSUE TITLE
Move this plugin into tox-dev?

### ISSUE THREAD

**Issue by obestwalter** [tox-dev/tox-pip-extensions#6]
Hi @asottile would you like to join the tox-dev org and move this into tox-dev?

If yes, let me know, then I invite you into the org and you can move it over.

**Comment by asottile** [comment]
@obestwalter would love to!

**Comment by obestwalter** [comment]
Great! Invitation is in your mail :)

**Comment by asottile** [comment]
Happy to be part of the team!
